# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=100)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyportal.Department')),
            ],
        ),
    ]
