# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('past_papers', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='notes',
        ),
        migrations.AddField(
            model_name='materials',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyportal.Subject'),
        ),
    ]
