# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0004_auto_20170302_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Depart',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dept_name',
        ),
    ]
