# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0005_auto_20170304_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depart',
            new_name='Department',
        ),
    ]
