# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0007_subject_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
