# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0008_subject_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_favorite',
        ),
    ]
