# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0010_auto_20170326_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_link',
            field=models.CharField(max_length=1000),
        ),
    ]
