# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0015_auto_20170329_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='dept_name', chained_model_field='dept_name', on_delete=django.db.models.deletion.CASCADE, to='studyportal.Subject'),
        ),
    ]
